language: go
go:
  - 1.12
env:
  - GO111MODULE=on
before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0
script:
  - go test -v ./...
  - golangci-lint run ./...
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success https://discordapp.com/api/webhooks/555254106974060545/yPx-St26M5J3Pwi5PMWLM-JGsxHBxCaccf56GR5i8ipqZ6bA4Jyyu5fut4UXBToim15h
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure https://discordapp.com/api/webhooks/555254106974060545/yPx-St26M5J3Pwi5PMWLM-JGsxHBxCaccf56GR5i8ipqZ6bA4Jyyu5fut4UXBToim15h
